bdtask_contractor/contractor/urls.py
from django.urls import path
from .views import *
from .renewal_views import *
from .upgrade_views import *


urlpatterns = [
    # frontend urls
    path('', HomeView.as_view(), name='home'),

    # enrollment urls
    path('enrollment/step-1/', EnrollmentStep1View.as_view(), name='enrollment-step-1'),
    path('enrollment/step-2/', EnrollmentStep2View.as_view(), name='enrollment-step-2'),
    path('enrollment/step-3/', EnrollmentStep3View.as_view(), name='enrollment-step-3'),
    path('enrollment/step-4/', EnrollmentStep4View.as_view(), name='enrollment-step-4'),
    path('enrollment/step-5/', EnrollmentStep5View.as_view(), name='enrollment-step-5'),

    # renewal urls

    path('renewal/step-1/', renewalView.as_view(), name='renewal-step-1'),
    path('renewal/step-2/', RenewalStep2View.as_view(), name='renewal-step-2'),
    path('renewal/step-3/', RenewalStep3View.as_view(), name='renewal-step-3'),
    path('renewal/step-4/', RenewalStep4View.as_view(), name='renewal-step-4'),
    path('renewal/step-5/', RenewalStep5View.as_view(), name='renewal-step-5'),

    # license upgrade

    path('license-upgrade/step-1/', UpgradeView.as_view(), name='license-upgrade-step-1'),
    path('license-upgrade/step-2/', UpgradeViewStep2.as_view(), name='license-upgrade-step-2'),
    path('license-upgrade/step-3/', UpgradeViewStep3.as_view(), name='license-upgrade-step-3'),
    path('license-upgrade/step-4/', UpgradeViewStep4.as_view(), name='license-upgrade-step-4'),
    path('license-upgrade/step-5/', UpgradeViewStep5.as_view(), name='license-upgrade-step-5'),

    path('profile-page/', ProfileView, name='profile-page'),
    path('contractor-preview-view/<int:pk>/', ContractorPreviewView, name='contractor_preview_view'),

    path('partners/delete/<int:id>/', deletePartnerView, name='partner-delete'),
    path('reg/delete/<int:id>/', regdeleteView, name='reg-delete'),
    path('worklist/delete/<int:id>/', worklistdeleteView, name='worklist-delete'),
    path('worklistc2/delete/<int:id>/', worklistc2deleteView, name='worklistc2-delete'),
    path('worklistc3/delete/<int:id>/', worklistc3deleteView, name='worklistc3-delete'),
    path('machinery/delete/<int:id>/', machinerydeleteView, name='machinery-delete'),
    path('technical/delete/<int:id>/', technicaldeleteView, name='technical-delete'),

    path('machineryd2/delete/<int:id>/', machineryd2deleteView, name='machineryd2-delete'),
    path('annexf/delete/<int:id>/', annexFDelete, name='annexf-delete'),
    path('vat/delete/<int:id>/', vatDelete, name='vat-delete'),
    path('tin/delete/<int:id>/', tinDelete, name='tin-delete'),

    # path('worklistForm/', worklistForm, name='worklistForm'),
    # path('worklistFormc2/', worklistFormc2, name='worklistFormc2'),
    # path('worklistFormc3/', worklistFormc3, name='worklistFormc3'),
    # path('listofeqipment/', listofeqipment, name='listofeqipment'),
    path('listofeqipmentd2/', listofeqipmentd2, name='listofeqipmentd2'),
    path('listtechnical/', listtechnical, name='listtechnical'),

    path('contact/', ContactView.as_view(), name='contact'),
    path('guidelines/', GuideLineView.as_view(), name='guideline'),

    path('approved-contractor-list-view/', approved_contractor_list_view, name='approved_contractor_list_view'),
    path('contractor-list-view/<str:role>/<str:division>/', contractor_list_view, name='contractor_list_view'),
    path('metting/', mettingCall, name='call-for-metting'),
    path('meetting-list', meettingList, name='meetting_list'),
    path('metting/<int:id>/', mettingEditCall, name='edit-call-for-metting'),

    path('contractor-details-view/<int:pk>/', ContractorDetailsView, name='contractor_details_view'),
    path('contractor-details-view-backend/<int:pk>/', ContractorDetailsViewBackend,
         name='contractor_details_view_backend'),

    path('assesment-form/<int:id>/', assesmentView, name='assesment_form'),
    path('pdf-contractor-list/', GeneratePdf.as_view(), name='contractor_pdf_view'),
    path('success-url/', successView, name='success-url'),
    path('failure-url/', failureView, name='failure-url'),

    path('contractor_form_submit/', contractor_form_submit, name='contractor_form_submit'),
    path('renewal_form_submit/', renewal_form_submit, name='renewal_form_submit'),
    path('upgrade_form_submit/', upgrade_form_submit, name='upgrade_form_submit'),


    path('ssl-payment/<int:tran_type>/', integrate_ssl_commrz, name='ssl-payment'),
    path('ssl-payment-renewal/<int:tran_type>/', integrate_ssl_commrz_renewal, name='ssl-payment-renewal'),
    path('ssl-payment-upgrade/<int:tran_type>/', integrate_ssl_commrz_upgrade, name='ssl-payment-upgrade'),
    path('chalan-ssl-payment/', integrate_chalan_ssl_commrz, name='chalan-ssl-payment'),

    # Chalan start
    # path('add_chalan/', ChalanView.as_view(), name='add_chalan'),
    path('add_chalan/', ChalanView, name='add_chalan'),
    path('chalan-list/', ChalanListBack.as_view(), name="chalan-list"),
    path('getContractorInfo/<int:pk>/', getContractor, name="getContractor"),
    path('addLicense/', addLicenseView, name='add-license'),
    path('print_preview/<int:pk>', PrintPreview, name='print_preview'),
    path('print_license/<int:pk>', print_license_preview, name='print_license'),
    path('contractor_license/<int:pk>', contractorLicensePreview, name="contractor_license"),

    # Contractor Chalan

    path('download/', ChalanList.as_view(), name="download"),
    path('license_list/', LicenseList.as_view(), name="license_list"),
    path('frontend_contractor_license/<int:pk>/', contractorLicensePreview, name="frontend_contractor_license"),
    path('frontend_print_license/<int:pk>/', contractor_print_license_preview, name='frontend_print_license'),
    path('chalan-payment/', chalanPayment, name='chalan-payment')

]

bdtask_contractor/wasa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contractor.urls')),
    path('', include('set_module.urls')),
    path('', include('accounts.urls'))
]
if settings.DEBUG:
    urlpatterns = urlpatterns + \
                  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
                  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bdtask_contractor/contractor/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()
from django.utils import timezone


# Create your models here.


class Contractor(models.Model):
    application_choices = (('enrollment', 'enrollment'),
                           ('renewal', 'renewal'),
                           ('upgrade', 'upgrade'))

    application_division = (
        ('3', 'Civil'),
        ('1', 'Civil and Supplier'),
        ('4', 'Electrical & Mechanical'),
        ('2', 'Electrical & Mechanical and Supplier'),
        ('5', 'Supplier')
    )

    trade_license_area = (
        ('dhaka_north', 'Dhaka North City Corporation'),
        ('dhaka_south', 'Dhaka South City Corporation '),
        ('narayanganj', 'Narayanganj City Corporation'))

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    proprietor_name = models.CharField(max_length=50, blank=True, null=True)
    contractor_name = models.CharField(max_length=50, blank=True)
    fathers_name = models.CharField(max_length=255, blank=True, null=True)
    mothers_name = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    position_in_firm = models.CharField(max_length=55, blank=True, null=True)
    mailing_address = models.CharField(max_length=255, blank=True)
    office_address = models.CharField(max_length=255, blank=True)
    # fax_no = models.CharField(max_length=255, blank=True)
    fax_no = models.IntegerField(blank=True, null=True)
    doc_with_signature = models.FileField(upload_to='Documents/', blank=True)
    NID_attachment = models.FileField(upload_to='NID/', blank=True)
    NID_NUMBER = models.IntegerField(blank=True, null=True)
    trade_license_no = models.CharField(max_length=255, blank=True)
    trade_license = models.FileField(upload_to='trade_license/', blank=True)
    non_judicial_stamp = models.FileField(upload_to='stamp/', blank=True)
    has_partners = models.BooleanField(default=False)
    declaration_agreement = models.BooleanField(default=False)
    photograph = models.ImageField(upload_to='photograph/', blank=True)
    applied_for = models.CharField(max_length=55, choices=application_choices, blank=True, null=True)
    application_division = models.CharField(max_length=55, choices=application_division, blank=True, null=True)
    trade_license_area = models.CharField(max_length=55, choices=trade_license_area, blank=True, null=True)
    old_license_number = models.CharField(max_length=255, blank=True, null=True)
    old_license_copy = models.FileField(blank=True, upload_to='license/')
    class_name = models.CharField(max_length=10, blank=True, null=True)
    upgraded_class = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return str(self.contractor_name) + ' - ' + str(self.applied_for) + ' - ' + str(
            self.get_application_division_display())


@receiver(post_save, sender=User)
def contractor_from_user_registration(sender, created, instance, *args, **kwargs):
    if created and instance and instance.roles == 'CONTRACTOR':
        Contractor.objects.create(user=instance)


post_save.connect(contractor_from_user_registration, sender=User)


class ContractorPartners(models.Model):
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
    partner_name = models.CharField(max_length=255)
    fathers_name = models.CharField(max_length=255, blank=True)
    address = models.CharField(max_length=255, blank=True)
    position_in_firm = models.CharField(max_length=55, blank=True)
    mothers_name = models.CharField(max_length=55, blank=True)

    def __str__(self):
        return self.partner_name


class ProfessionalTechnical(models.Model):
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
    certificate_of_incorporation = models.FileField(upload_to='certificate_of_incorporation/', blank=True)
    judicial_stamp = models.FileField(upload_to='judicial_stamp/', blank=True, null=True)
    has_registered = models.BooleanField(default=False)
    has_general_certificate = models.BooleanField(default=False)
    general_certificate_1 = models.FileField(upload_to='general_certificate/', blank=True)
    general_certificate_2 = models.FileField(upload_to='general_certificate/', blank=True)
    list_of_work_annex_c1 = models.BooleanField(default=False)
    list_of_work_annex_c2 = models.BooleanField(default=False)
    list_of_work_annex_c3 = models.BooleanField(default=False)
    list_of_work_annex_d1 = models.BooleanField(default=False)
    desc_of_work_annex_d2 = models.BooleanField(default=False)
    list_of_work_e1 = models.BooleanField(default=False)

    def __str__(self):
        return str(self.contractor)


class DetailsRegistration(models.Model):
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
    name_of_dept = models.CharField(max_length=55, blank=True)
    enlisted_class = models.CharField(max_length=55, blank=True)
    last_renewal_date = models.DateTimeField(blank=True, null=True)
    enlistment_date_RegNo = models.CharField(max_length=255, blank=True)
    file_attachment = models.FileField(upload_to='details_registration/', blank=True)

    def __str__(self):
        return self.name_of_dept


class ListOfWork(models.Model):
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
    name_of_work = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    contractor_amount = models.IntegerField()
    start_date = models.DateTimeField(blank=True, null=True)
    delivery_date = models.DateTimeField(blank=True, null=True)
    remarks = models.CharField(max_length=255)
    contact_no = models.CharField(max_length=255)
    completion_certificate = models.FileField(upload_to='details_registration/', blank=True)

    def __str__(self):
        return self.name_of_work


class ListOfWorkC2(models.Model):
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
    name_of_work = models.CharField(max_length=255)
    contact_no = models.CharField(max_length=55)
    client = models.CharField(max_length=255)
    contact_amount = models.IntegerField()
    start_date = models.DateTimeField(blank=True, null=True)
    delivery_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=55)
    progress_certificate = models.FileField(upload_to='details_registration/', blank=True)

    def __str__(self):
        return self.name_of_work


class ListOfWorkC3(models.Model):
    role_applicant = (('Prime Contractor/Supplier', 'Prime Contractor/Supplier'),
                      ('Subcontractor/Partner', 'Subcontractor/Partner'),
                      ('partner in JVC', 'partner in JVC'))
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
    contact_name = models.CharField(max_length=255)
    contact_number = models.CharField(max_length=255)
    name_of_client = models.CharField(max_length=255)
    date = models.DateTimeField(blank=True, null=True)
    address = models.CharField(max_length=255)
    role = models.CharField(max_length=55, choices=role_applicant, default='prime_contractor')
    amount_of_contact = models.IntegerField()
    applicant_share = models.IntegerField()
    reason = models.TextField()
    date_commencement_contract = models.CharField(max_length=255)
    time_for_completion = models.CharField(max_length=255)
    completation_date = models.DateTimeField()
    explanation = models.TextField()
    description_of_work = models.TextField()
    responsibility = models.TextField()

    def __str__(self):
        return str(self.contact_name)


class ListOfMachinery(models.Model):
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
    name_of_eqipment = models.CharField(max_length=55, blank=True)
    manufacture = models.CharField(max_length=55, blank=True)
    capacity = models.CharField(max_length=55, blank=True)
    year_of_model = models.CharField(max_length=55, blank=True)
    status = models.CharField(max_length=55, blank=True)
    ownership = models.CharField(max_length=55, blank=True)
    remarks = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name_of_eqipment


class ListOfMachineryD2(models.Model):
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
    name_of_eqipment = models.CharField(max_length=55, blank=True)
    manufacture = models.CharField(max_length=55, blank=True)
    capacity = models.CharField(max_length=55, blank=True)
    year_of_model = models.CharField(max_length=55, blank=True)
    status = models.CharField(max_length=55, blank=True)
    ownership = models.CharField(max_length=55, blank=True)
    remarks = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name_of_eqipment


class ListofTechnical(models.Model):
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE, blank=True, null=True)
    name_of_employee = models.CharField(max_length=255, blank=True)
    designation = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='technical_personal')

    def __str__(self):
        return self.name_of_employee


class FinancialCapacity(models.Model):
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
    name_of_the_banker = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    telephone = models.CharField(max_length=255)
    fax = models.CharField(max_length=255)
    email = models.EmailField()
    contact_name = models.CharField(max_length=255)
    attached_file = models.FileField(upload_to='attached-file/', blank=True)
    year_1_total_assets = models.FloatField()

bdtask_contractor/contractor/templates/contractor/license/backend/backend_print_license.html
{% extends 'base.html' %}

{% block content%}



<div style="background-color: #e8e8e8;height: 100vh;padding: 30px;font-size: 14px;" >
            <div class="text-right">
        <center> <button class="btn btn-success btn-sm mr-1" id="btnPrint99" onclick="printDiv('printableArea')"><i class="fas fa-print mr-1"></i>Print</button></center>
                    </div>
            <div style="max-width: 960px;margin-right: auto;margin-left: auto;"  id="printableArea">

                <div style="background-color: #fff;padding: 50px;font-size: large;">
                    <div>
                        <div style="display: -ms-flexbox;display: flex;-ms-flex-wrap: wrap;flex-wrap: wrap;margin-right: -30px;">
                        <div style="-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;position: relative;width: 100%;padding-right: 30px;padding-left: 30px;align-items: flex-start;display: flex;flex-direction: column;border-right: 1px solid #ddd;">
                            <img id="applicant_id"   alt="" style="height: 80px;border: 1px solid #ddd;margin: 0 auto 10px;display: block" src="{% if license.contractor.photograph.url %}{{ license.contractor.photograph.url }}{% endif %}">
                             <div style="font-weight: 600; margin-bottom: 5px;">মালিক/স্বত্বাধিকারীর নামঃ </div>
                            <ul style="list-style: none;padding: 0;margin: 0 0 30px;">
                                <li style="font-weight: 600; margin-bottom: 10px;">জনাবঃ&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;" id="proprietor_name">{{ license.contractor.proprietor_name }}</span></li>
                                <li style="font-weight: 600; margin-bottom: 10px;">পিতার নামঃ&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;" id="contractor_father">{{ license.contractor.fathers_name }}</span></li>
                                <li style="font-weight: 600; margin-bottom: 10px;">মাতার নামঃ&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;" id="contractor_mother">{{ license.contractor.mothers_name }}</span></li>
                                <li style="font-weight: 600; margin-bottom: 10px;">নমুনা স্বাক্ষরঃ</li>
                                <li style="font-weight: 600; margin-bottom: 10px;display: flex;align-items: center;"><span>১।</span>&nbsp;<img class="signature-img" src="img/signature-01.png" alt="" style="max-width: 100%;height: 24px;border-bottom: 1px dashed #000;"></li>
                                <li style="font-weight: 600; margin-bottom: 10px;display: flex;align-items: center;"><span>২।</span>&nbsp;<img class="signature-img" src="img/signature-02.png" alt="" style="max-width: 100%;height: 24px;border-bottom: 1px dashed #000;"></li>
                                <li style="font-weight: 600; margin-bottom: 10px;display: flex;align-items: center;"><span>৩।</span>&nbsp;<img class="signature-img" src="img/signature-03.png" alt="" style="max-width: 100%;height: 24px;border-bottom: 1px dashed #000;"></li>
                                <li style="font-weight: 600; margin-bottom: 10px;">তারিখঃ&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;">২৭-২-২০১৯</span></li>
                            </ul>
                            <div style="margin-left: auto;margin-top: auto;">
                                <div style="display: inline-block;text-align: center;font-weight: 600;font-size: 13px;">
                                    <img class="signature-img" src="img/signature-03.png" alt="" style="max-width: 100%;height: 24px;display: block;margin: 0 auto 10px;">
                                    ২৭-২-২০১৯<br>
                                    উপ-সচিব <br>
                                    প্রশাসন বিভাগ - ২, ঢাকা ওয়াসা<br>
                                    ও<br>
                                    সদস্য-সচিব,<br>
                                    এনলিস্টমেন্ট কমিটি।
                                </div>
                            </div>
                        </div>
                        <div style="-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;position: relative;width: 100%;padding-right: 30px;padding-left: 30px;align-items: flex-start;display: flex;flex-direction: column;">
                            <ul style="list-style: none;padding: 0;margin: 0 0 30px;">
                                <li style="font-weight: 600; margin-bottom: 10px;">১। ঠিকাদারি প্রতিষ্ঠানের নামঃ&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;" id="contractor_name"> {{ license.contractor.contractor_name }}</span></li>
                                <li style="font-weight: 600; margin-bottom: 10px;">২।ঠিকানাঃ</li>
                                <li style="font-weight: 600; margin-bottom: 10px;">
                                    <ul style="list-style: none;margin: 0;">
                                        <li style="font-weight: 600; margin-bottom: 10px;"><span>(ক) বর্তমানঃ</span>&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;">{{ license.contractor.address }}</span></li>
                                        <li style="font-weight: 600; margin-bottom: 10px;"><span>(খ) স্থায়ীঃ</span>&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;">৫১/৩, মানিকনগর, সবুজবাগ, ঢাকা।</span></li>
                                    </ul>
                                </li>
                                <li style="font-weight: 600; margin-bottom: 10px;">৩। শ্রেণীঃ&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;" id="class_name">  {{ chalan.class_type }}</span></li>
                                <li style="font-weight: 600; margin-bottom: 10px;">৪।  পূর্ত কাজ/ সরবরাহ কাজ/ <del>বৈদ্যুতিক ও যান্ত্রিক কাজ</del></li>
                                <li style="font-weight: 600; margin-bottom: 10px;">৫। নিবন্ধন সংখ্যা/ নম্বরঃ&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;" id="endlishment_no"> {{ license.enlishment_no }}</span></li>
                                <li style="font-weight: 600; margin-bottom: 10px;">৬। তালিকাভুক্তির বৎসরঃ&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;" id="enlishment_year">{{ license.enlishment_year }}</span></li>
                                <li style="font-weight: 600; margin-bottom: 10px;">৭। শ্রেণী উন্নীতকরণ/ নবায়নঃ&nbsp;<span style="font-weight: normal;border-bottom: 1px dashed #000;" id="class_upgradation"> {{ license.upgradataion_or_renewal_year }} </span> পর্যন্ত।</li>
                            </ul>
                            <div style="margin-left: auto;margin-top: auto;">
                                <div style="display: inline-block;text-align: center;font-weight: 600;font-size: 13px;">
                                    <img class="signature-img" src="img/signature-02.png" alt="" style="max-width: 100%;height: 24px;display: block;margin: 0 auto 10px;">
                                    ২৭-২-২০১৯<br>
                                    উপ-সচিব <br>
                                    প্রশাসন বিভাগ - ২, ঢাকা ওয়াসা<br>
                                    ও<br>
                                    সদস্য-সচিব,<br>
                                    এনলিস্টমেন্ট কমিটি।
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>

                </div>
            </div>
        </div>

        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
        -->

<style type="text/css">

   <!--
      @media screen {
         p.bodyText {font-family:verdana, arial, sans-serif;}
      }

      @media print {
         #printableArea.bodyText {font-family:georgia, times, serif;font-size: large;}
      }
      @media screen, print {
         p.bodyText {font-size:10pt}
      }
   -->

</style>
{%  endblock content %}



{% block custom_js %}

<script>

            function printDiv(divName) {
                             var printContents = document.getElementById(divName).innerHTML;
                             var originalContents = document.body.innerHTML;
                             document.body.innerHTML = printContents;
                             window.print();
                             document.body.innerHTML = originalContents;
                         }

             $("#download").addClass("active");

             $("#license").addClass("active");
             $("#add-license").addClass("mm-active");

             $(document).ready(function() {
             $('.select2').select2({
                    theme: "classic"
                });

             $('#id_enlishment_no').keyup(function () {
                $('#endlishment_no').text($(this).val());
             });

             $('#id_enlishment_year').keyup(function () {
                $('#enlishment_year').text($(this).val());
             });

             $('#id_upgradataion_or_renewal_year').keyup(function () {
                $('#class_upgradation').text($(this).val());
             });


             //Ajax

             $('#id_contractor').change(function(){
                 var contractor_id = $(this).val();

                 //alert(contractor_id);

                       $.ajax({
                            method: 'GET',
                            'contentType': 'application/json',
                            url: '/getContractorInfo/'+contractor_id + '/',

                            dataType: 'json',
                            success: function (data) {
                              if (data.contractor_info) {
                                console.log(data.contractor_info[0].applied_for);
                                $('#contractor_father').text(data.contractor_info[0].fathers_name);
                                $('#contractor_mother').text(data.contractor_info[0].mothers_name);
                                if(data.contractor_info[1].class_name ==='second_class'){

                                    $('#class_name').text('দ্বিতীয়');
                                }
                                else if(data.contractor_info[1].class_name ==='third_class'){
                                    $('#class_name').text('তৃতীয়');

                                }

                                else if(data.contractor_info[1].class_name ==='first_class'){
                                    $('#class_name').text('প্রথম');

                                }
                                else{

                                    $('#class_name').text();
                                }




                                $('#contractor_name').text(data.contractor_info[0].contractor_name);
                                $('#proprietor_name').text(data.contractor_info[0].proprietor_name);
                                //$('#applicant_id').src = (data.contractor_info[0].photograph.url);
                                //$('#applicant_id').src = 'hi';
                                  var photoGraph = (data.contractor_info[0].photograph);


                                var base_url = window.location.origin;

                                photoGraph = (base_url+'/media/'+photoGraph);

                                 $("#applicant_id").attr("src",photoGraph);

                                alert(base_url);
                              }
                            }
                          });

              });


    $("#btnPrint").on("click", function () {
            var divContents = $("#printableArea").html();
            var printWindow = window.open('', '', 'height=400,width=800');
            printWindow.document.write('<html><head><title>DIV Contents999</title>');
            printWindow.document.write('</head><body >');
            printWindow.document.write(divContents);
            printWindow.document.write('</body></html>');
            printWindow.document.close();
            printWindow.print();
            window.onafterprint = printWindow.close(); // this is our magic


        });


             //End
             });



</script>

{% endblock custom_js %}